apply strict compilation flags and fix function prototypes
Several functions in server/ were not specifying an argument list,
ie they were declared as void foo(); When compiling with -Wstrict-prototypes,
this leads to:
  platform/stm32f4/rcc.c:19:6: error: function declaration isn't a prototype