lib: resolve conflict type definition
Resolve the following error,
  In file included from arm-2013.05/bin/../lib/gcc/arm-none-eabi/4.7.3/
                      ../../../../arm-none-eabi/include/stdio.h:34:0,
                 from kernel/start.c:26:
                      arm-2013.05/bin/../lib/gcc/arm-none-eabi/4.7.3/
                      include/stddef.h:213:23: error: conflicting types for 'size_t'
  In file included from include/platform/debug_uart.h:9:0,
                 from kernel/start.c:13:
    include/types.h:17:18: note: previous declaration of 'size_t' was here

Signed-off-by: Viller Hsiao <villerhsiao@gmail.com>